server:
  port: ${ENV_SERVER_PORT:8889}
scheduler:
  thread-pool-size: ${ENV_SCHEDULER_THREAD_POOL_SIZE:10}
  max-attempts: ${ENV_SCHEDULER_MAX_ATTEMPTS:3}
  initial-delay-after-payment-request: ${ENV_SCHEDULER_INITIAL_DELAY_AFTER_PAYMENT_REQUEST:30}
  period-between-attempts: ${ENV_SCHEDULER_PERIOD_BETWEEN_ATTEMPTS:30}
spring:
  datasource:
    url: ${ENV_DB_CONNECTION_URL:jdbc:mysql://localhost:3306/checkout.com}
    username: ${ENV_DB_USERNAME:root}
    password: ${ENV_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
checkout:
  urls:
    payment-url: ${ENV_ENDPOINT_PAYMENT_URL:/process}
    payment-callback-url: ${ENV_ENDPOINT_PAYMENT_CALLBACK_URL:/payment-callback}
  api:
    url: ${ENV_CHECKOUT_BASE_API_URL:https://api.sandbox.checkout.com}
    secret-key: ${ENV_CHECKOUT_SECRET_KEY:sk_sbox_gjhcrpnxkoaxhrsryafzz7cvoyw}
    public-api-key: ${ENV_CHECKOUT_PUBLIC_API_KEY:pk_sbox_wgxxlg53oyic7iluulf7xkm6ma2}
    processing-channel-id: ${ENV_CHECKOUT_PROCESSING_CHANNEL_ID:pc_fb6ptslj5hgureg6zvgq577z2a}
    callback-url-signature: ${ENV_CALLBACK_URL_SIGNATURE:dd32299f-553c-4c31-9c9f-d6854592256f}
client:
  allowed-origin: ${ENV_CLIENT_ALLOWED_ORIGIN:http://95.216.224.218:3000}
  success-url: ${ENV_CLIENT_SUCCESS_URL:/status}
  failure-url: ${ENV_CLIENT_FAILURE_URL:/failure}