server:
  port: 8889
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/checkout.com
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  secret-key: 123456
  expiration-millis: 9600000
checkout:
  api:
    url: https://api.sandbox.checkout.com
    secret-key: sk_sbox_gjhcrpnxkoaxhrsryafzz7cvoyw
    public-api-key: pk_sbox_wgxxlg53oyic7iluulf7xkm6ma2
    processing-channel-id: pc_fb6ptslj5hgureg6zvgq577z2a
    callback-url-signature: dd32299f-553c-4c31-9c9f-d6854592256f